name: SubReminder
options:
  bundleIdPrefix: com.subreminder
  deploymentTarget:
    macOS: "14.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
targets:
  SubReminder:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.subreminder.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Sources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
  SubReminderTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: SubReminder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.subreminder.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SubReminder.app/Contents/MacOS/SubReminder"
        BUNDLE_LOADER: "$(TEST_HOST)"
